# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor1', models.CharField(max_length=200)),
                ('sensor2', models.CharField(max_length=200)),
                ('sensor3', models.CharField(max_length=200)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
            ],
        ),
    ]
