# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0003_auto_20171121_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default=None, max_length=200)),
                ('city_latitude', models.FloatField(default=None)),
                ('city_longitude', models.FloatField(default=None)),
                ('sensor1', models.CharField(max_length=200)),
                ('sensor2', models.CharField(max_length=200)),
                ('sensor3', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='System1',
        ),
    ]
